version: "3.9"

services:
  sqlite:
    image: keinos/sqlite3:latest
    container_name: ecommerce-sqlite
    restart: always
    tty: true
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./sqlite:/db
      - ./sql:/sql
      - ./updates:/updates
